name: go-ci

on:
  push:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Golang
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: Cache
        uses: actions/cache@v2
        id: cache-go
        with:
          path: ~/go/pkg/mod
          key: ${{ env.cache-version }}-${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: make mod/download

      - name: Tools
        run: make tool/install

      - name: Lint
        run: make lint

  test:
    runs-on: ubuntu-latest
    steps:
      - name: MySQL
        uses: mirromutth/mysql-action@v1.1
        with:
          host port: 13306
          mysql version: 8.0
          mysql database: webapi
          mysql root password: P@ssw0rd

      - name: Checkout
        uses: actions/checkout@v3

      - name: Golang
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: Cache
        uses: actions/cache@v2
        id: cache-go
        with:
          path: ~/go/pkg/mod
          key: ${{ env.cache-version }}-${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: make mod/download

      - name: Tools
        run: make tool/install

      - name: Test & Cover
        run: make cover

      - name: Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: go-coverage
          path: go/reports/coverage.html
